import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import './globals.css';
import NavBar from '~/components/ui/NavBar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${GeistSans.className} flex flex-col h-screen w-full gap-3`}
      >
        <NavBar />
        <main className='flex-auto'>{children}</main>

        <footer className='footer footer-center p-4 bg-base-300 text-base-content'>
          <aside>
            <p>Copyright © 2023 - All right reserved by Kazte</p>
          </aside>
        </footer>
      </body>
    </html>
  );
}
